# Generated by Django 4.2.6 on 2023-10-31 18:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100)),
                ('bcat', models.CharField(max_length=100, verbose_name='category')),
                ('btitle', models.CharField(max_length=500, verbose_name='title')),
                ('bdate', models.DateField(default=datetime.datetime(2023, 10, 31, 23, 52, 43, 471130))),
                ('bshort_description', models.CharField(max_length=999, verbose_name='shortdesc')),
                ('bdescription', models.CharField(max_length=9999, verbose_name='description')),
                ('buid', models.ForeignKey(db_column='buid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
