# Generated by Django 4.2.6 on 2023-11-01 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblogs', '0002_alter_userblog_bdate_alter_userblog_bname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblog',
            name='bimages',
            field=models.ImageField(default=0, upload_to='userblogs', verbose_name='Images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userblog',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2023, 11, 2, 0, 13, 7, 409328), verbose_name='date'),
        ),
    ]
