# Generated by Django 4.2.6 on 2023-11-01 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblogs', '0003_userblog_bimages_alter_userblog_bdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2023, 11, 2, 0, 28, 8, 861191), verbose_name='date'),
        ),
    ]
