# Generated by Django 4.2.6 on 2023-11-01 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblogs', '0004_alter_userblog_bdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2023, 11, 2, 0, 31, 7, 171431), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='bimages',
            field=models.ImageField(upload_to='blogs', verbose_name='Images'),
        ),
    ]
