# Generated by Django 4.2.6 on 2023-11-03 08:14

import datetime
from django.db import migrations, models
import userblogs.models


class Migration(migrations.Migration):

    dependencies = [
        ('userblogs', '0006_alter_userblog_bdate_alter_userblog_bimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2023, 11, 3, 13, 44, 21, 275141), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='bimages',
            field=models.ImageField(upload_to=userblogs.models.Userblog, verbose_name='Images'),
        ),
    ]
