# Generated by Django 4.2.6 on 2023-11-03 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblogs', '0007_alter_userblog_bdate_alter_userblog_bimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2023, 11, 3, 14, 11, 14, 324548), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='bimages',
            field=models.ImageField(upload_to='userblogs', verbose_name='Images'),
        ),
    ]
