# Generated by Django 4.2.6 on 2023-11-06 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblogs', '0008_alter_userblog_bdate_alter_userblog_bimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2023, 11, 6, 14, 49, 12, 847735), verbose_name='date'),
        ),
    ]
