# Generated by Django 4.2.6 on 2023-11-06 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblogs', '0009_alter_userblog_bdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2023, 11, 6, 14, 56, 30, 728916), verbose_name='date'),
        ),
    ]
