# Generated by Django 4.2.6 on 2023-11-10 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userblogs', '0010_alter_userblog_bdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='bcat',
            field=models.CharField(choices=[('World', 'World'), ('Tech', 'Tech'), ('Business', 'Business'), ('Art-Design', 'Art-Design'), ('Entertainment', 'Entertainment')], max_length=100, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2023, 11, 10, 21, 23, 32, 422864), verbose_name='date'),
        ),
    ]
